apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fulfillment-order-service
  annotations:
    solace-queue-browser/queue-filter: fulfillment-order-svc    
spec:
  lifecycle: production
  owner: solace_test
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: The petstore API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: ./petstore.oas.yaml
